version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=colibri-test-349114-a30e8b514e6d.json
      - ENV=local
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - STORAGE_API_ENDPOINT=http://storage:4443
    volumes:
      - ./src:/work/src
      - ./data:/work/data
      - ./.circleci:/work/.circleci
      - ./requirements.txt:/work/requirements.txt
      - ./Dockerfile:/work/Dockerfile
      - ./Dockerfile-dev:/work/Dockerfile-dev
    ports:
      - 8000:80
  storage:
    image: fsouza/fake-gcs-server
    container_name: storage
    ports:
      - 4443:4443
    volumes:
      - ${PWD}/data:/data
    command: -scheme http
  firestore:
    image: almoustapha/firestore-emulator
    #container_name: firestore
    environment:
      - host=0.0.0.0:8080
    ports:
      - "8080:8080"
    
      




  
